### ISSUE TITLE
Enter ItemID doesnt work properly

### ISSUE THREAD

**Issue by med0rian** [wow-addon/FarmIt2#13]
Hello,
I don't know if this error is also due to the 10.0 bruteforce fix, but with this also no item ID's can be entered anymore. (CTRL+Right click)

Error in BugSack:
`5x Interface/AddOns/FarmIt2/FarmIt2_Button.lua:483: bad argument #1 to 'SetNumber' (outside of expected range -3.402823e+38 to 3.402823e+38 - Usage: self:SetNumber(number))
[string "=[C]"]: in function `SetNumber'
[string "@Interface/AddOns/FarmIt2/FarmIt2_Button.lua"]:483: in function 'FI_Edit_Item'
[string "@Interface/AddOns/FarmIt2/FarmIt2_Button.lua"]:256: in function <Interface/AddOns/FarmIt2/FarmIt2_Button.lua:189>

Locals:
(*temporary) = FI_Button_Edit_Item {
 0 = <userdata>
}
(*temporary) = ""
(*temporary) = "outside of expected range -3.402823e+38 to 3.402823e+38 - Usage: self:SetNumber(number)"
`

**Comment by karpana** [comment]
Hello @med0rian 
I've taken a look, and I've found a solution for this.

I've created created Pull Request #14 for this issue.
