### ISSUE TITLE
Pre Patch Compability

### ISSUE THREAD

**Issue by med0rian** [wow-addon/FarmIt2#18]
Since I can't get through the frame stuff very well, I just hope that someone else will be able to fix the problem. Otherwise it would be a pity about the addon

The "Help" window should open at startup, but something seems to have been changed again

````InterfaceOptions_AddCategory```` is deprecated since 10.0 so i think this is the problem

````
1x FarmIt2/FarmIt2_Config.lua:20: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@FarmIt2/FarmIt2_Config.lua"]:20: in main chunk

Locals:
yellow = "|cFFFFFF00"
green = "|cFF00FF00"
blue = "|cFF00CCFF"
white = "|cFFFFFFFF"
(*temporary) = nil
(*temporary) = FI_Panel {
 name = "FarmIt2"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
````

```` 2x FarmIt2/FarmIt2_Config.xml:70 Couldn't find frame parent: FI_Panel_1 ````
```` 2x FarmIt2/FarmIt2_Config.xml:157 Couldn't find frame parent: FI_Panel_2 ````
```` 2x FarmIt2/FarmIt2_Config.xml:190 Couldn't find frame parent: FI_Panel_3 ````
```` 2x FarmIt2/FarmIt2_Config.xml:223 Couldn't find frame parent: FI_Panel_4 ````
```` 2x FarmIt2/FarmIt2_Config.xml:296 Couldn't find frame parent: FI_Panel_5 ````

**Comment by davidcraig** [comment]
You are correct InterfaceOptions_AddCategory was removed in DF, I've updated the refences of these calls, however right clicking doesn't seem to bring up any actual config, but I'm not sure what that ought to look like, perhaps someone later will advise if there is further changes to add :) v11.0.1 now has these fixes
