### ISSUE TITLE
Oct 29th Cata patch - broken again

### ISSUE THREAD

**Issue by roweboy1974** [wow-addon/FarmIt2#21]
Today's Firelands prepatch broke this like the Phase 5 patch of SOD did last month. It worked great until today. Not sure how to fix this so if someone can, that would be great.

Thank you!

**Comment by med0rian** [comment]
Hi,
do you have [BugSack](https://www.curseforge.com/wow/addons/bugsack)/[BugGrabber ](https://www.curseforge.com/wow/addons/bug-grabber)installed?

There should be a error message that mentioned FarmIt2. This would help to locate where the error comes from.

**Comment by roweboy1974** [comment]
Yes I do. Sorry I forgot to posts the error:

1x FarmIt2/FarmIt2_Config.lua:18: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@FarmIt2/FarmIt2_Config.lua"]:18: in main chunk

Locals:
yellow = "|cFFFFFF00"
green = "|cFF00FF00"
blue = "|cFF00CCFF"
white = "|cFFFFFFFF"
(*temporary) = nil
(*temporary) = FI_Panel {
 name = "FarmIt"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"

**Comment by med0rian** [comment]
This deprecated Codeline is not in the actual Code anymore :D
Fixed in PR e81911f
When you download
[FarmIt2.zip](https://github.com/user-attachments/files/17592003/FarmIt2.zip) and extract it to your FarmIt2 folder, this specific error should be gone.

**Comment by roweboy1974** [comment]
That worked! thank you! Not sure how it broke considering I didn't update that addon since it was fixed for SOD P5.

**Comment by roweboy1974** [comment]
thank you
