### ISSUE TITLE
Setting Currency Objective shows an error the first time

### ISSUE THREAD

**Issue by rapozab** [wow-addon/FarmIt2#4]
The first time I right click on a currency to set the objective I get:

Message: FI_Currency_1_Editbox: Set bytes attribute on EditBox element instead of child FontString
Time: Fri Nov 20 07:21:56 2020
Count: 1

Afterward, I get the following (this is that "name is a table" issue again:
Message: Interface\AddOns\FarmIt2\FarmIt2_Core.lua:951: attempt to concatenate field 'name' (a table value)
Time: Fri Nov 20 08:45:22 2020
Count: 1
Stack: Interface\AddOns\FarmIt2\FarmIt2_Core.lua:951: attempt to concatenate field 'name' (a table value)
[string "@Interface\AddOns\FarmIt2\FarmIt2_Core.lua"]:951: in function `FI_Set_Objective'
[string "@Interface\AddOns\FarmIt2\FarmIt2_Currency.lua"]:465: in function <Interface\AddOns\FarmIt2\FarmIt2_Currency.lua:442>

Locals: tbl_name = "Currencies"
rec_id = 1
amount = 9
data = <table> {
 count = 0
 success = false
 objective = 9
 id = 1
 lastcount = 0
 icon = ""
 name = <table> {
 }
}
f_name = nil
message = nil
sound = nil
color = <table> {
 1 = 1
 2 = 1
 3 = 1
 4 = "FFFFFF"
}
(*temporary) = "Farming objective set:  "
(*temporary) = 9
(*temporary) = " "
(*temporary) = <table> {
 currencyTypesID = 1754
 quantity = 8
 name = "Argent Commendation"
 iconFileID = 236690
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate field 'name' (a table value)"

**Comment by rapozab** [comment]
Also, currency tracking doesn't work.

**Comment by davidcraig** [comment]
I've pushed up some more changes.

**Comment by davidcraig** [comment]
Closing as assuming fixed, if not please re-open :)
