### ISSUE TITLE
command issue

### ISSUE THREAD

**Issue by johjoh3105** [wow-addon/FarmIt2#6]
/farmit add doesn't work

**Comment by karpana** [comment]
I don't believe that was ever a valid command. 

The docs indicate that you might need to use
/Farmit group add


(https://www.curseforge.com/wow/addons/farmit/pages/commands)

**Comment by johjoh3105** [comment]
> I don't believe that was ever a valid command.
> 
> The docs indicate that you might need to use
> /Farmit group add
> 
> (https://www.curseforge.com/wow/addons/farmit/pages/commands)

you are correct. my brain was just not working properly XD
thanks.
